### ISSUE TITLE
Creating timer thread failed!!

### ISSUE THREAD

**Issue by gokul-gokz** [ROBOTIS-GIT/ROBOTIS-Documents#2]
Whenver I launch the file manipulator_h_ manager of the ROBOTIS-MANIPULATOR-H package, the node fails throwing the error,

>  Creating timer thread failed!!
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument

How to fix this?
`

**Comment by wilsonz91** [comment]
You need to run the launch file as su, see [here](https://github.com/ROBOTIS-GIT/ROBOTIS-Framework/issues/12)
